### ISSUE TITLE
Aruco Android

### ISSUE THREAD

**Issue by Meett98** [RivoLink/Aruco-Android#17]
Hii @RivoLink Meet here.......

**Comment by RivoLink** [comment]
Hi @Meett98 
Do you have add all OpenCV native libraries to your project ?

**Comment by Meett98** [comment]
Yes @RivoLink I added all the native libraries.

**Comment by Meett98** [comment]
Hey @RivoLink  i Generate the graph of tvecs x and y coordinates and i also add the button in main activity after pressing that button the app will generate the graph of tvecs x and y coordinates .But now i want every time i capture aruco from main activity then the last detected x,y coordinates will be added in graph for example if i detect aruco 3 times then graph have 3 points plotted so how this can be done??  And it is urgent so please can you give me solution as soon as you have.

Thank You.

**Comment by RivoLink** [comment]
Hi @Meett98,

**Comment by RivoLink** [comment]
Hi @Meett98,
I don't understand your problem, just add a new point when you detect a marker.

**Comment by Meett98** [comment]
So @RivoLink  my problem is this. 
I created a button in main activity and create an intent so when we press that button it will go to second activity which I created. In this second activity I draw a 2d graph of x and y coordinates of tvecs. So i want that every time i go from main activity to second activity the x, y points should be drawn on the existing graph but it creates a new graph every time. So this is my problem I want that points will added into existing graph untill i close the app.

**Comment by RivoLink** [comment]
If I understood correctly, the FirstActivity (MainActivity) detects the marker, and the SecondActivity draws the graph?

If you don't want to recreate the graph, you can make it a unit class

```
class Graph {

    public static Graph instance;

    private Graph(){}

    public static Graph getInstance(){
        if(instance == null){
            instance = new Graph();
        }

        return instance;
    }

    public function addNode(float x, float y){
        // ...
    }

    // ...
}
```

In MainActivity

```
Graph graph = Graph.getInstance();
graph.addNode(x, y);
```

**Comment by Meett98** [comment]
I will add nodes in main activity then how can i draw the graph from second activity? 
@RivoLink

**Comment by RivoLink** [comment]
Just draw with your draw method

```
Graph graph = Graph.getInstance();
graph.draw();
```

Graph is an unit class so it's unique

**Comment by Meett98** [comment]
hjdhjds
`
       chart = (LineChart) findViewById(R.id.line_charrrrrrrrrrt);
       Graph graph= Graph.getInstance();
       graph.draw(chart);`

**Comment by Meett98** [comment]
I tried but can not get it here i share both code can you please tell me which things i should write and where? It will really helpful if you help me.


In MainActivity i passing intent in OnCameraFrame function so here is the code

`
	@Override
	public Mat onCameraFrame(CameraBridgeViewBase.CvCameraViewFrame inputFrame){
		if(!CameraParameters.isLoaded()){
			return inputFrame.rgba();
		}

		Imgproc.cvtColor(inputFrame.rgba(), rgb, Imgproc.COLOR_RGBA2RGB);
		gray = inputFrame.gray();

		ids = new MatOfInt();
		corners.clear();



		Aruco.detectMarkers(gray, dictionary,corners, ids, parameters);

		if(corners.size()>0){
			Aruco.drawDetectedMarkers(rgb, corners, ids);

			rvecs = new Mat();
			tvecs = new Mat();

			Aruco.estimatePoseSingleMarkers(corners, SIZE, cameraMatrix, distCoeffs,rvecs,tvecs);

			for(int i = 0;i < ids.toArray().length;i++)
			{

				float distance = (float)Math.sqrt((tvecs.get(i,0)[0] * tvecs.get(i,0)[0]) + (tvecs.get(i,0)[1] * tvecs.get(i,0)[1])
				 + (tvecs.get(i,0)[2]*tvecs.get(i,0)[2])) * 50;


				Aruco.drawAxis(rgb, cameraMatrix, distCoeffs, rvecs.row(i), tvecs.row(i), SIZE/2.0f);


				Mat coordinates = corners.get(i); //get item in List
				List<Point> corners_xy = new ArrayList<>(4);
				for (int r = 0; r < coordinates.rows(); r++) {
					for (int c = 0; c < coordinates.cols(); c++) {
						corners_xy.add(new Point((int)coordinates.get(r,c)[0], (int)coordinates.get(r,c)[1])); // x,y point
					}
				}

				Point top_left = corners_xy.get(0);
				Point top_right = corners_xy.get(1);

				float x = (float)tvecs.get(i,0)[0]*50;
				float y = (float)tvecs.get(i,0)[1]*50;
				float z = (float)tvecs.get(i,0)[2]*50;




				xvalue = x;
				yvalue = y;

				String text = String.format("X: %.03f,  Y: %.03f,  Z: %.03f", x,y,z);
				String dist = String.format("Distance : %f" , distance);

				Point text_position = new Point(
						rgb.cols()/2,
						rgb.rows()/2
				);

				Point text_position_dist = new Point(
						rgb.cols()/1.5,
						rgb.rows()/1.5
				);

				int font_face = Core.FONT_HERSHEY_SIMPLEX;
				double font_scale = 0.75;
				Scalar font_color = new Scalar(255, 0, 1);

				Imgproc.putText(rgb, text, text_position, font_face, font_scale, font_color,3);

				Imgproc.putText(rgb, dist, text_position_dist, font_face, font_scale, font_color,3);
			}

		}

			entries.add(new Entry(xvalue,yvalue));

			//the button which i created in main activity
			btngo = (Button) findViewById(R.id.btngo);
			btngo.setOnClickListener(new View.OnClickListener() {
				@Override
				public void onClick(View view) {
					Intent igo = new Intent(MainActivity.this, SecondMainActivity.class);
					intent.putExtra("Entries", entries);
					startActivity(igo);
				}
			});







		return rgb;
	}
`





Code of SecondActivity.java

`   protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        setContentView(R.layout.activity_second_main);


        Intent intent = getIntent();

       
 Entry entries = intent.getParcelableExtra("Entries");




       chart = (LineChart) findViewById(R.id.line_charrrrrrrrrrt);
      



       LineDataSet dataSet = new LineDataSet(entries, "Label");
        dataSet.setColor(Color.BLUE);
        dataSet.setValueTextColor(Color.BLACK);

        LineData lineData = new LineData(dataSet);
        chart.setData(lineData);
        chart.invalidate();


    }`



And also can you please give the full code of class Graph.



And is there any chance that we can make a handler of graph so that it can handle and update the existing graph.If this can the solution then can you please give the code of that.

**Comment by RivoLink** [comment]
This code seems to work...
Share with me the error, I don't understand what exactly you want.
Tell me in one sentence the problem, or what you want.

**Comment by Meett98** [comment]
@RivoLink the problem is I want to add all points in existing graph but it creates every time a new graph.

**Comment by RivoLink** [comment]
It's normal, you alternate between 2 Activities and passing the data forces you to recreate the graph.
If you don't want to recreate graph, use 2 Fragments in one Activity

**Comment by RivoLink** [comment]
I'm sorry but it's not in the scope of this project

Here is a tutorial you can follow : [Fragments in Android with Sample Tutorial](https://www.meghandev.io/post/copy-of-fragments-in-android-part-i)
