### ISSUE TITLE
OpenCVLoader.initDebug() failing on Android 11

### ISSUE THREAD

**Issue by lahirurlt** [RivoLink/Aruco-Android#4]
Hi, OpenCVLoader.initDebug() is failing on an Android 11 phone. Any tips on how to resolve?

Thanks for your work on this.

**Comment by nubcake94** [comment]
I also have the same problem.
`java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_java3.so" not found`

I did my research and found that I am supposed to install OpenCV Manager from play store, which is not there any more :)

Any ideas how to run this project? Would be a great help for my university studies.
