### ISSUE TITLE
OpenCVLoader.initDebug() failing

### ISSUE THREAD

**Issue by nubcake94** [RivoLink/Aruco-Android#6]
`java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_java3.so" not found`

I did my research and found that I am supposed to install OpenCV Manager from play store, which is not there any more :)

Any ideas how to run this project? Would be a great help for my university studies.

**Comment by nubcake94** [comment]
related to #4

**Comment by RivoLink** [comment]
Hi, 

Download the libraries here:
https://github.com/RivoLink/opencv-android/tree/master/opencv3_4_4_contrib/native/libs

Then, paste all in the directory of the project:
https://github.com/RivoLink/Aruco-Android/tree/master/opencv344-contrib/src/main/jniLibs

Tell me if that doesn't help you.

**Comment by nubcake94** [comment]
Hi,

I am really grateful for your quick response.

The informations you provided me helped building and running the project.
I'll take some time and update the project's README for you, and open a pull request. So that others can know this as well :)
