### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [RivoLink/Aruco-Android#7]
Which license is Aruco using itself? I could not find a license file in the project's root, nor a mention in the Readme. Couldyou please clarify? Thanks!

**Comment by RivoLink** [comment]
All the features of Aruco are only accessible in opencv-contrib, so you have to refer to the [license](opencv344-contrib/LICENSE) of opencv-contrib.
Otherwise, you can check the Aruco [sourceforge](https://sourceforge.net/projects/aruco/files)  page.

**Comment by IzzySoft** [comment]
Thanks for your reply, @RivoLink! This raises 3 questions:

> All the features of Aruco are only accessible in opencv-contrib

Does that mean users need to install something in addition to this app to make it work – or are you rather saying that branch is what the app is based on?

> so you have to refer to the license of opencv-contrib.

The link gives me a 404.

> Otherwise, you can check the Aruco sourceforge page.

Ah. That says "BSD" – which is totally fine, thanks! So maybe including that with the Readme? Or even add the license file to the project root, so Github picks it up automatically?

**Comment by RivoLink** [comment]
You are welcome, 

- No, we do not need any other installion to run the application, it already uses opencv-contrib to have all the features of Aruco.
- Sorry, I copied the wrong link, try this: [LICENSE](https://github.com/RivoLink/Aruco-Android/blob/master/opencv344-contrib/LICENSE)
- Ok, I will add the license in the README

**Comment by RivoLink** [comment]
You are welcome, 

- No, we do not need any other installion to run the application, it already uses opencv-contrib to have all the features of Aruco.
- Sorry, I copied the wrong link, try this: [LICENSE](https://github.com/RivoLink/Aruco-Android/blob/master/opencv344-contrib/LICENSE)
- Ok, I will add the license in the README

Thanks for your attention

**Comment by IzzySoft** [comment]
Thanks a lot! I've just added both apps (i.e. including the camera calibration) to [my repo](https://apt.izzysoft.de/fdroid) to make them easier to find and access, including automated updates (which are automatically fetched within 24h of your attaching them to a new tag). A few pointers:

* please always increase `versionCode` with each release, as that's how Android tells versions apart
* please take a look at [this report](https://www.virustotal.com/gui/file/0d946789121652ce601f9afd1540f52fa1e47e53277b50182b752099d64a9653/detection/f-0d946789121652ce601f9afd1540f52fa1e47e53277b50182b752099d64a9653-1641555433). It's most likely "false positives", but you're better aware of them.
* both apps lack a dedicated icon (they're using the Android default icon). I saw this with several apps already – so if someone has multiple such candidates installed they are hard to distinguish in the launcher :wink:
* both APKs have debugging enabled. I guess that's due to their "early state", and you'll remove the debug flag in some later version. Just mentioning it "to remember" :wink:

With the next sync around 19:00 UTC today, your apps can be found here:

* [Aruco](https://apt.izzysoft.de/fdroid/index/apk/mg.rivolink.app.aruco)
* [Aruco Camera Calibration](https://apt.izzysoft.de/fdroid/index/apk/mg.rivolink.app.aruco.camera.calibration)

So if you wish, you can use [these badges](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) in your Readme to link there, for easier installation/updates by your users.

Now, wishing you the best for your project – and thanks again for your help!

**Comment by RivoLink** [comment]
Thank you very much, I will follow your recommendations for the next update.

**Comment by IzzySoft** [comment]
Great! Listings are visible now, btw. As the issue is thereby solved, I think we can close it. Should you wish the metadata in [Fastlane Structures](https://gitlab.com/snippets/1895688) so you can control how the listings look, let me know and I send my initial package with a PR (as you have 2 apps here, and Fastlane covers only one, I'd suggest using it for the main app). My updater would check that structure as well for news then whenever a new release is pulled.
